"""add_preferred_language

Revision ID: 23d3e403cd62
Revises: 2b3b75111a5a
Create Date: 2026-10-05 18:31:17.875267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23d3e403cd62'
down_revision: Union[str, None] = '2b3b75111a5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('preferred_language', sa.Text(), server_default='hi', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'preferred_language')
    # ### end Alembic commands ###
