"""extend challan schema: packaging adjustments, audit table, format metadata

Revision ID: 2b3b75111a5a
Revises: f5c288e9ff4d
Create Date: 2026-09-18 13:33:37.336363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b3b75111a5a'
down_revision: Union[str, None] = 'f5c288e9ff4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_extraction_audit',
    sa.Column('audit_id', sa.Text(), nullable=False),
    sa.Column('invoice_id', sa.Text(), nullable=False),
    sa.Column('ocr_raw_text', sa.Text(), nullable=True),
    sa.Column('vision_llm_raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_used', sa.Text(), nullable=False),
    sa.Column('escalated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('merchant_edited_fields', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('invoice_packaging_adjustments',
    sa.Column('adjustment_id', sa.Text(), nullable=False),
    sa.Column('invoice_id', sa.Text(), nullable=False),
    sa.Column('item_name', sa.Text(), nullable=False),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ),
    sa.PrimaryKeyConstraint('adjustment_id')
    )
    op.add_column('invoice_line_items', sa.Column('raw_text', sa.Text(), nullable=True))
    op.add_column('invoice_line_items', sa.Column('unit', sa.Text(), nullable=True))
    op.add_column('invoice_line_items', sa.Column('hsn_code', sa.Text(), nullable=True))
    op.add_column('invoice_line_items', sa.Column('is_free_scheme', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('invoice_line_items', 'quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.add_column('invoices', sa.Column('challan_type', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('capture_medium', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('challan_number', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('distributor_gstin', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('vehicle_number', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('payment_handle_type', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('payment_handle_value', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('tax_cgst', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('tax_sgst', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('tax_igst', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('additional_charges', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'additional_charges')
    op.drop_column('invoices', 'tax_igst')
    op.drop_column('invoices', 'tax_sgst')
    op.drop_column('invoices', 'tax_cgst')
    op.drop_column('invoices', 'payment_handle_value')
    op.drop_column('invoices', 'payment_handle_type')
    op.drop_column('invoices', 'vehicle_number')
    op.drop_column('invoices', 'distributor_gstin')
    op.drop_column('invoices', 'challan_number')
    op.drop_column('invoices', 'capture_medium')
    op.drop_column('invoices', 'challan_type')
    op.alter_column('invoice_line_items', 'quantity',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('invoice_line_items', 'is_free_scheme')
    op.drop_column('invoice_line_items', 'hsn_code')
    op.drop_column('invoice_line_items', 'unit')
    op.drop_column('invoice_line_items', 'raw_text')
    op.drop_table('invoice_packaging_adjustments')
    op.drop_table('invoice_extraction_audit')
    # ### end Alembic commands ###
