"""initial schema: merchants, customers, distributors, ledger_transactions, invoices, invoice_line_items, settlement_daily_rollups, outbox_events, insight_cache, alerts

Revision ID: f5c288e9ff4d
Revises: 
Create Date: 2026-09-18 02:22:13.750710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5c288e9ff4d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('merchant_id', sa.Text(), nullable=False),
    sa.Column('shop_name', sa.Text(), nullable=False),
    sa.Column('owner_name', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('cognee_dataset', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('merchant_id'),
    sa.UniqueConstraint('cognee_dataset'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('alerts',
    sa.Column('alert_id', sa.Text(), nullable=False),
    sa.Column('merchant_id', sa.Text(), nullable=False),
    sa.Column('alert_type', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.Text(), nullable=False),
    sa.Column('merchant_id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('canonical_key', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('merchant_id', 'canonical_key', name='uq_customer_merchant_canonical')
    )
    op.create_table('distributors',
    sa.Column('distributor_id', sa.Text(), nullable=False),
    sa.Column('merchant_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('upi_id', sa.Text(), nullable=True),
    sa.Column('canonical_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('distributor_id'),
    sa.UniqueConstraint('merchant_id', 'canonical_key', name='uq_distributor_merchant_canonical')
    )
    op.create_table('insight_cache',
    sa.Column('cache_key', sa.Text(), nullable=False),
    sa.Column('merchant_id', sa.Text(), nullable=False),
    sa.Column('insight_type', sa.Text(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('stale_after', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_table('outbox_events',
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('merchant_id', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), server_default='PENDING', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('idx_outbox_pending', 'outbox_events', ['status', 'created_at'], unique=False, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_table('settlement_daily_rollups',
    sa.Column('rollup_id', sa.Text(), nullable=False),
    sa.Column('merchant_id', sa.Text(), nullable=False),
    sa.Column('rollup_date', sa.Date(), nullable=False),
    sa.Column('upi_collection_total', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('payout_total', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('net_balance', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('rollup_id'),
    sa.UniqueConstraint('merchant_id', 'rollup_date', name='uq_settlement_merchant_date')
    )
    op.create_table('invoices',
    sa.Column('invoice_id', sa.Text(), nullable=False),
    sa.Column('merchant_id', sa.Text(), nullable=False),
    sa.Column('distributor_id', sa.Text(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_paid', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payout_reference', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.distributor_id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    op.create_table('ledger_transactions',
    sa.Column('txn_id', sa.Text(), nullable=False),
    sa.Column('merchant_id', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('txn_type', sa.Text(), nullable=False),
    sa.Column('items', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('extraction_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('txn_id')
    )
    op.create_index('idx_ledger_customer', 'ledger_transactions', ['merchant_id', 'customer_id'], unique=False)
    op.create_index('idx_ledger_date', 'ledger_transactions', ['merchant_id', 'created_at'], unique=False)
    op.create_table('invoice_line_items',
    sa.Column('line_item_id', sa.Text(), nullable=False),
    sa.Column('invoice_id', sa.Text(), nullable=False),
    sa.Column('distributor_id', sa.Text(), nullable=False),
    sa.Column('sku', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.distributor_id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ),
    sa.PrimaryKeyConstraint('line_item_id')
    )
    op.create_index('idx_line_item_rate_lookup', 'invoice_line_items', ['distributor_id', 'sku', 'invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_line_item_rate_lookup', table_name='invoice_line_items')
    op.drop_table('invoice_line_items')
    op.drop_index('idx_ledger_date', table_name='ledger_transactions')
    op.drop_index('idx_ledger_customer', table_name='ledger_transactions')
    op.drop_table('ledger_transactions')
    op.drop_table('invoices')
    op.drop_table('settlement_daily_rollups')
    op.drop_index('idx_outbox_pending', table_name='outbox_events', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_table('outbox_events')
    op.drop_table('insight_cache')
    op.drop_table('distributors')
    op.drop_table('customers')
    op.drop_table('alerts')
    op.drop_table('merchants')
    # ### end Alembic commands ###
